version: '3.5'

services:
  app:
    build: ./
    container_name: 'python3.9-django4.1-cmake-base'
    working_dir: /app
    command: /usr/local/bin/init.sh
    ports:
      - 8000:8000
      - 2222:2222
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
